server:
  grpc_listen_port: 9097 # to avoid conflict with tempo

metastore:
  address: 127.0.0.1
  min_ready_duration: 1s

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    min_ready_duration: 1s

pyroscopedb:
  data_path: "/data/pyroscope"
  # Retention - keep profiling data for 90 days
  retention_period: 2160h

# Compactor for cleanup
compactor:
  compaction_interval: 1h
  blocks_retention_period: 2160h     # 90 days
